
import { ContentItem, Elements } from '@kentico/kontent-delivery';

/**
 * Generated by '@kentico/kontent-model-generator@3.2.0'
 
 */
export class BrightcoveVideo extends ContentItem {
        constructor() {
        super({
            propertyResolver: ((elementName) => {
                if (elementName === 'video_iframe') {
                    return 'videoIframe';
                }
                if (elementName === 'video_title') {
                    return 'videoTitle';
                }
                return elementName;
            })
        });
    }
}
