
import { ContentItem, Elements } from '@kentico/kontent-delivery';

/**
 * Generated by '@kentico/kontent-model-generator@3.2.0'
 
 */
export class CallToAction extends ContentItem {
        constructor() {
        super({
            propertyResolver: ((elementName) => {
                if (elementName === 'internal_asset__pdf__doc__etc_') {
                    return 'internalAssetPdfDocEtc';
                }
                if (elementName === 'external_url') {
                    return 'externalUrl';
                }
                if (elementName === 'open_in_new_window_') {
                    return 'openInNewWindow';
                }
                if (elementName === 'call_to_action') {
                    return 'callToAction';
                }
                return elementName;
            })
        });
    }
}
