
import { ContentItem, Elements } from '@kentico/kontent-delivery';

/**
 * Generated by '@kentico/kontent-model-generator@3.2.0'
 
 */
export class ExternalLink extends ContentItem {
        constructor() {
        super({
            propertyResolver: ((elementName) => {
                if (elementName === 'link_title') {
                    return 'linkTitle';
                }
                if (elementName === 'new_tab_') {
                    return 'newTab';
                }
                if (elementName === 'link_target') {
                    return 'linkTarget';
                }
                return elementName;
            })
        });
    }
}
