
import { ContentItem, Elements } from '@kentico/kontent-delivery';

/**
 * Generated by '@kentico/kontent-model-generator@3.2.0'
 
 */
export class Footer extends ContentItem {
        constructor() {
        super({
            propertyResolver: ((elementName) => {
                if (elementName === 'contact_email') {
                    return 'contactEmail';
                }
                if (elementName === 'contact_phone') {
                    return 'contactPhone';
                }
                if (elementName === 'external_links') {
                    return 'externalLinks';
                }
                return elementName;
            })
        });
    }
}
