
import { ContentItem, Elements } from '@kentico/kontent-delivery';

/**
 * Generated by '@kentico/kontent-model-generator@3.2.0'
 
 */
export class Homepage extends ContentItem {
        constructor() {
        super({
            propertyResolver: ((elementName) => {
                if (elementName === 'hero_image') {
                    return 'heroImage';
                }
                if (elementName === 'mecp_logo') {
                    return 'mecpLogo';
                }
                if (elementName === 'hero_text') {
                    return 'heroText';
                }
                if (elementName === 'promo_zone') {
                    return 'promoZone';
                }
                if (elementName === 'intro_text') {
                    return 'introText';
                }
                if (elementName === 'page_title') {
                    return 'pageTitle';
                }
                if (elementName === 'hero_links') {
                    return 'heroLinks';
                }
                return elementName;
            })
        });
    }
}
