
import { ContentItem, Elements } from '@kentico/kontent-delivery';

/**
 * Generated by '@kentico/kontent-model-generator@3.2.0'
 
 */
export class Image extends ContentItem {
        constructor() {
        super({
            propertyResolver: ((elementName) => {
                if (elementName === 'float_direction') {
                    return 'floatDirection';
                }
                if (elementName === 'margin_left') {
                    return 'marginLeft';
                }
                if (elementName === 'alt_tag') {
                    return 'altTag';
                }
                if (elementName === 'margin_right') {
                    return 'marginRight';
                }
                if (elementName === 'margin_bottom') {
                    return 'marginBottom';
                }
                if (elementName === 'margin_top') {
                    return 'marginTop';
                }
                return elementName;
            })
        });
    }
}
