
import { ContentItem, Elements } from '@kentico/kontent-delivery';

/**
 * Generated by '@kentico/kontent-model-generator@3.2.0'
 
 */
export class PageButton extends ContentItem {
        constructor() {
        super({
            propertyResolver: ((elementName) => {
                if (elementName === 'button_text') {
                    return 'buttonText';
                }
                if (elementName === 'external_page_link') {
                    return 'externalPageLink';
                }
                if (elementName === 'open_in_new_tab') {
                    return 'openInNewTab';
                }
                if (elementName === 'internal_page_link') {
                    return 'internalPageLink';
                }
                return elementName;
            })
        });
    }
}
