
import { ContentItem, Elements } from '@kentico/kontent-delivery';

/**
 * Generated by '@kentico/kontent-model-generator@3.2.0'
 
 */
export class Page extends ContentItem {
        constructor() {
        super({
            propertyResolver: ((elementName) => {
                if (elementName === 'widget_zone') {
                    return 'widgetZone';
                }
                if (elementName === 'alternate_slugs') {
                    return 'alternateSlugs';
                }
                return elementName;
            })
        });
    }
}
