
import { ContentItem, Elements } from '@kentico/kontent-delivery';

/**
 * Generated by '@kentico/kontent-model-generator@3.2.0'
 
 */
export class Promo extends ContentItem {
        constructor() {
        super({
            propertyResolver: ((elementName) => {
                if (elementName === 'background_image') {
                    return 'backgroundImage';
                }
                if (elementName === 'linked_page') {
                    return 'linkedPage';
                }
                return elementName;
            })
        });
    }
}
