
import { ContentItem, Elements } from '@kentico/kontent-delivery';

/**
 * Generated by '@kentico/kontent-model-generator@3.2.0'
 
 */
export class SimpleCopy extends ContentItem {
        constructor() {
        super({
            propertyResolver: ((elementName) => {
                if (elementName === 'image_style') {
                    return 'imageStyle';
                }
                if (elementName === 'widget_name') {
                    return 'widgetName';
                }
                if (elementName === 'section_title') {
                    return 'sectionTitle';
                }
                return elementName;
            })
        });
    }
}
