
import { ContentItem, Elements } from '@kentico/kontent-delivery';

/**
 * Generated by '@kentico/kontent-model-generator@3.2.0'
 
 */
export class SimplePage extends ContentItem {
        constructor() {
        super({
            propertyResolver: ((elementName) => {
                if (elementName === 'navigation__sub_navigation_title') {
                    return 'navigationSubNavigationTitle';
                }
                if (elementName === 'navigation__navigation') {
                    return 'navigationNavigation';
                }
                return elementName;
            })
        });
    }
}
